server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        # 1. TRASA ELEMENTS SERVICE (RELACJE) - MUSI BYĆ BARDZIEJ SZCZEGÓŁOWA
        - id: elements_route_relations
          uri: ${URL_ELEMENT:http://element-service:8082} # Cel: elements-service
          predicates:
            # POPRAWIONA SKŁADNIA: Używamy */trails/** dla relacji mountains/{id}/trails
            # * dopasowuje segment ID góry.
            - Path=/api/mountains/*/trails/**
          filters:
            - StripPrefix=0

        # 2. TRASA ELEMENTS SERVICE (STANDARDOWE SZLAKI)
        - id: elements_route_trails
          uri: ${URL_ELEMENT:http://element-service:8082} # Cel: elements-service
          predicates:
            # Łapie /api/trails, /api/trails/{id}
            - Path=/api/trails/**
          filters:
            - StripPrefix=0

        # 3. TRASA CATEGORY SERVICE (GÓRY) - NAJBARDZIEJ OGÓLNA
        - id: category_route
          uri: ${URL_CATEGORY:http://category-service:8081} # Cel: category-service
          predicates:
            - Path=/api/mountains/**
          filters:
            - StripPrefix=0