server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        # 1. TRASA ELEMENTS SERVICE (RELACJE) - MUSI BYĆ BARDZIEJ SZCZEGÓŁOWA
        - id: elements_route_relations
          uri: lb://element-service # Cel: elements-service
          predicates:
            # POPRAWIONA SKŁADNIA: Używamy */trails/** dla relacji mountains/{id}/trails
            # * dopasowuje segment ID góry.
            - Path=/api/mountains/*/trails/**
          filters:
            - StripPrefix=0

        # 2. TRASA ELEMENTS SERVICE (STANDARDOWE SZLAKI)
        - id: elements_route_trails
          uri: lb://element-service # Cel: elements-service
          predicates:
            # Łapie /api/trails, /api/trails/{id}
            - Path=/api/trails/**
          filters:
            - StripPrefix=0

        # 3. TRASA CATEGORY SERVICE (GÓRY) - NAJBARDZIEJ OGÓLNA
        - id: category_route
          uri: lb://category-service # Cel: category-service
          predicates:
            - Path=/api/mountains/**
          filters:
            - StripPrefix=0
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true